"""Standard SQL model — arbitrary queries over plain PostgreSQL/Nucleus."""
struct SQLModel
    conn::LibPQ.Connection
end

"""
    query(m::SQLModel, sql, params...) -> NamedTuple of column vectors

Execute a SELECT and return results as a Tables.jl columntable (NamedTuple of
column vectors). With DataFrames.jl loaded, wrap in DataFrame(...) for a full
DataFrame.
"""
function query(m::SQLModel, sql_str::String, params...)
    result = LibPQ.execute(m.conn, sql_str, collect(params))
    return Tables.columntable(result)
end

"""
    query_one(m::SQLModel, sql, params...) -> NamedTuple row

Execute a SELECT and return the first row as a NamedTuple. Throws NucleusError
(404) if no rows are returned.
"""
function query_one(m::SQLModel, sql_str::String, params...)
    result = LibPQ.execute(m.conn, sql_str, collect(params))
    rows = Tables.rowtable(result)
    isempty(rows) && throw(NucleusError(
        "https://neutron.dev/errors/not-found",
        "Not Found",
        404,
        "Query returned no rows"))
    return first(rows)
end

"""
    execute!(m::SQLModel, sql, params...) -> Int64

Execute an INSERT/UPDATE/DELETE and return the number of affected rows.
"""
function execute!(m::SQLModel, sql_str::String, params...)::Int64
    result = LibPQ.execute(m.conn, sql_str, collect(params))
    # `num_affected_rows` throws ArgumentError("Result generated by an
    # incompatible command") for anything that is not INSERT/UPDATE/DELETE, so
    # execute! could not run CREATE TABLE, BEGIN, COMMIT or ROLLBACK at all —
    # it raised rather than returning 0. DDL and transaction control are the
    # two most common things a caller reaches for after an INSERT.
    return try
        Int64(LibPQ.num_affected_rows(result))
    catch e
        e isa ArgumentError ? Int64(0) : rethrow()
    end
end
