// Auto-generated by Neutron. Do not edit.
declare module "neutron/content" {
  interface ContentCollectionMap {
    "units": { "id": string; "title": string; "slug": string; "section": string; "chapter": string; "concept_catalog_id": string; "prerequisites": string[]; "successors": string[]; "tier_anchors": { "beginner": string | "deferred" | unknown; "intermediate": string | "deferred" | unknown; "master": string | "deferred" | unknown; }; "tiers_present": "beginner" | "intermediate" | "master"[]; "pending_prereqs": boolean; "references": { "source": string; "path": string; "locator"?: string; "pending"?: boolean; "pointer"?: string; }[]; "lean_module"?: string; "lean_status": "full" | "partial" | "none"; "lean_mathlib_gap"?: string; "human_reviewer"?: string; "estimated_time"?: unknown; "status": "draft" | "review" | "approved" | "shipped"; "produced_by"?: string; "reviewed_by": string[]; };
  }
}
