"""Independent PostgreSQL oracle. No Neutron compiler or codec imports."""
from __future__ import annotations
import json
import os
import sys
from protocol import PROTOCOL, validate_request, redact

MARKER = 'neutron-polyglot-conformance-v1:'

def execute(request: dict, connect=None) -> dict:
    validate_request(request)
    if request['case_id'] != 'scalar-extremes':
        raise ValueError('unknown oracle case')
    url = os.environ.get('NEUTRON_TEST_DATABASE_URL')
    if not url:
        raise ValueError('NEUTRON_TEST_DATABASE_URL required')
    if connect is None:
        import psycopg
        connect = psycopg.connect
    # schema_scope is generated by runner; marker binds cleanup to this request.
    scope = request['schema_scope']
    token = request.get('ownership_token', '')
    if not isinstance(token, str) or len(token) != 64 or any(c not in '0123456789abcdef' for c in token):
        raise ValueError('invalid ownership token')
    import psycopg.sql as sql
    with connect(url) as conn:
        with conn.cursor() as cur:
            action = request['action']
            if action == 'setup':
                # Never IF NOT EXISTS: preexisting objects cannot be claimed.
                cur.execute(sql.SQL('CREATE SCHEMA {}').format(sql.Identifier(scope)))
                cur.execute(sql.SQL('COMMENT ON SCHEMA {} IS {}').format(sql.Identifier(scope), sql.Literal(MARKER + token)))
                cur.execute(sql.SQL('CREATE TABLE {}.values_fixture (id integer PRIMARY KEY, big bigint, precise numeric, moment timestamptz, sql_null text, document jsonb)').format(sql.Identifier(scope)))
                cur.execute(sql.SQL("INSERT INTO {}.values_fixture VALUES (1, 9223372036854775807, 12345678901234567890.123456789, '2024-01-02 03:04:05.123456+00', NULL, 'null'::jsonb)").format(sql.Identifier(scope)))
                rows = []
            else:
                cur.execute('SELECT pg_catalog.obj_description(oid, %s) FROM pg_catalog.pg_namespace WHERE nspname = %s', ('pg_namespace', scope))
                marker = cur.fetchone()
                if marker is None and action == 'cleanup':
                    return {'protocol': PROTOCOL, 'case_id': request['case_id'], 'status': 'pass', 'rows': [], 'oracle': 'native-postgresql-text-v1'}
                if marker is None or marker[0] != MARKER + token:
                    raise ValueError('schema ownership marker mismatch')
                if action == 'cleanup':
                    cur.execute(sql.SQL('DROP SCHEMA {} CASCADE').format(sql.Identifier(scope)))
                    rows = []
                else:
                    # SQL text output avoids Python/Neutron numeric and temporal codecs.
                    cur.execute("SET LOCAL TIME ZONE 'UTC'")
                    cur.execute(sql.SQL('SELECT id::text, big::text, precise::text, moment::text, sql_null IS NULL, document::text FROM {}.values_fixture ORDER BY id').format(sql.Identifier(scope)))
                    rows = [list(row) for row in cur.fetchall()]
    return {'protocol': PROTOCOL, 'case_id': request['case_id'], 'status': 'pass', 'rows': rows, 'oracle': 'native-postgresql-text-v1'}

def main():
    try:
        request = json.load(sys.stdin)
        print(json.dumps(execute(request)))
        return 0
    except Exception as exc:
        print(json.dumps({'status': 'fail', 'diagnostics': redact(str(exc), os.environ.get('NEUTRON_TEST_DATABASE_URL', ''))}))
        return 1

if __name__ == '__main__':
    raise SystemExit(main())
