// Auto-generated by Neutron. Do not edit.
declare module "@neutron-build/core" {
  interface NeutronGeneratedRouteMap {
    paths:
    | "/"
    | "/blog"
    | `/blog/${string}`
    | "/cli"
    | "/client"
    | "/desktop"
    | "/docs"
    | "/docs/*slug"
    | "/elixir"
    | "/go"
    | "/julia"
    | "/lean"
    | "/modelica"
    | "/mojo"
    | "/native"
    | "/nucleus"
    | "/orm"
    | "/python"
    | "/quint"
    | "/rss/xml"
    | "/rust"
    | "/studio"
    | "/typescript"
    | "/web"
    | "/zig"
  }
}

export {};
