// Auto-generated by Neutron. Do not edit.
declare module "neutron/content" {
  interface ContentCollectionMap {
    "blog": { "title": string; "description": string; "pubDate": Date; "author": string; "tags": string[]; "draft": boolean; };
    "docs": { "title": string; "description"?: string; };
  }
}
