// Command neutron-ormgen generates typed Go ORM column bundles from explicit
// mapped struct tags. It requires no database and ships in the Go SDK module.
package main

import (
	"bytes"
	"crypto/sha256"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strconv"
	"strings"
)

const ormPath = "github.com/neutron-build/neutron/go/orm"

type mappedField struct{ name, typ, db string }

func main() {
	dir := flag.String("dir", ".", "model package directory")
	model := flag.String("type", "", "mapped struct type")
	out := flag.String("out", "", "generated filename within model package")
	check := flag.Bool("check", false, "compare output without writing")
	flag.Parse()
	if *model == "" || *out == "" || filepath.Base(*out) != *out || !strings.HasSuffix(*out, ".go") {
		fmt.Fprintln(os.Stderr, "ormgen: -type and a .go output filename within -dir are required")
		os.Exit(1)
	}
	result, err := generate(*dir, *model)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	path := filepath.Join(*dir, *out)
	if *check {
		existing, err := os.ReadFile(path)
		if err != nil || !bytes.Equal(existing, result) {
			fmt.Fprintln(os.Stderr, "ormgen: generated model drift; regenerate the column bundle")
			os.Exit(1)
		}
		return
	}
	if existing, err := os.ReadFile(path); err == nil && !bytes.HasPrefix(existing, []byte("// Code generated by neutron-ormgen; DO NOT EDIT.")) {
		fmt.Fprintln(os.Stderr, "ormgen: refusing to overwrite a non-generated source file")
		os.Exit(1)
	}
	if err := os.WriteFile(path, result, 0644); err != nil {
		fmt.Fprintln(os.Stderr, "ormgen: output write failed")
		os.Exit(1)
	}
}

func generate(dir, model string) ([]byte, error) {
	set := token.NewFileSet()
	packages, err := parser.ParseDir(set, dir, func(info os.FileInfo) bool { return !strings.HasSuffix(info.Name(), "_test.go") }, parser.ParseComments)
	if err != nil {
		return nil, fmt.Errorf("ormgen: model source parse failed")
	}
	var owner *ast.File
	var structure *ast.StructType
	var packageName string
	for name, pkg := range packages {
		for _, file := range pkg.Files {
			for _, declaration := range file.Decls {
				generic, ok := declaration.(*ast.GenDecl)
				if !ok {
					continue
				}
				for _, spec := range generic.Specs {
					typ, ok := spec.(*ast.TypeSpec)
					if !ok || typ.Name.Name != model {
						continue
					}
					if structure != nil {
						return nil, fmt.Errorf("ormgen: duplicate target model")
					}
					if typ.TypeParams != nil {
						return nil, fmt.Errorf("ormgen: generic mapped model unsupported")
					}
					value, ok := typ.Type.(*ast.StructType)
					if !ok {
						return nil, fmt.Errorf("ormgen: target must be a struct")
					}
					owner = file
					structure = value
					packageName = name
				}
			}
		}
	}
	if structure == nil || owner == nil {
		return nil, fmt.Errorf("ormgen: target struct not found")
	}
	imports := map[string]string{}
	for _, item := range owner.Imports {
		path, err := strconv.Unquote(item.Path.Value)
		if err != nil {
			return nil, fmt.Errorf("ormgen: invalid import")
		}
		name := filepath.Base(path)
		if item.Name != nil {
			name = item.Name.Name
		}
		imports[name] = path
	}
	used := map[string]string{}
	fields := []mappedField{}
	seen := map[string]bool{}
	fieldCount := 0
	for _, field := range structure.Fields.List {
		count := len(field.Names)
		if count == 0 {
			count = 1
		}
		fieldCount += count
		if field.Tag == nil {
			return nil, fmt.Errorf("ormgen: every field needs an explicit db tag")
		}
		tag, err := strconv.Unquote(field.Tag.Value)
		if err != nil {
			return nil, fmt.Errorf("ormgen: invalid field tag")
		}
		db, ok := reflect.StructTag(tag).Lookup("db")
		if !ok || db == "" {
			return nil, fmt.Errorf("ormgen: missing explicit db tag")
		}
		if db == "-" {
			continue
		}
		if len(field.Names) != 1 || !ast.IsExported(field.Names[0].Name) {
			return nil, fmt.Errorf("ormgen: mapped embedded/unexported/shared-tag fields unsupported")
		}
		parts := strings.Split(db, ",")
		if len(parts) > 2 || (len(parts) == 2 && parts[1] != "nullable") || parts[0] == "" || len([]byte(parts[0])) > 63 || strings.ContainsRune(parts[0], 0) {
			return nil, fmt.Errorf("ormgen: invalid mapped db tag")
		}
		if seen[parts[0]] {
			return nil, fmt.Errorf("ormgen: duplicate mapped db column")
		}
		seen[parts[0]] = true
		value := field.Type
		pointer, nullable := value.(*ast.StarExpr)
		if nullable {
			value = pointer.X
		}
		if nullable != (len(parts) == 2) {
			return nil, fmt.Errorf("ormgen: pointer/nullability tag mismatch")
		}
		if err := validateType(value, imports, used); err != nil {
			return nil, err
		}
		var printed bytes.Buffer
		if err := format.Node(&printed, set, field.Type); err != nil {
			return nil, fmt.Errorf("ormgen: field type formatting failed")
		}
		fields = append(fields, mappedField{field.Names[0].Name, printed.String(), db})
	}
	if len(fields) == 0 {
		return nil, fmt.Errorf("ormgen: model has no mapped fields")
	}
	ormAlias := "orm"
	for alias, path := range used {
		if path == ormPath {
			ormAlias = alias
		}
	}
	for used[ormAlias] != "" && used[ormAlias] != ormPath {
		ormAlias += "x"
	}
	used[ormAlias] = ormPath
	reflectAlias := "__neutron_reflect"
	for used[reflectAlias] != "" {
		reflectAlias += "x"
	}
	used[reflectAlias] = "reflect"
	fmtAlias := "__neutron_fmt"
	for used[fmtAlias] != "" {
		fmtAlias += "x"
	}
	used[fmtAlias] = "fmt"
	var shape bytes.Buffer
	fmt.Fprintf(&shape, "%s\n%d\n", model, fieldCount)
	for _, field := range fields {
		fmt.Fprintf(&shape, "%s\t%s\t%s\n", field.name, field.typ, field.db)
	}
	digest := sha256.Sum256(shape.Bytes())
	var result bytes.Buffer
	fmt.Fprintf(&result, "// Code generated by neutron-ormgen; DO NOT EDIT.\npackage %s\n\nimport (\n", packageName)
	aliases := make([]string, 0, len(used))
	for alias := range used {
		aliases = append(aliases, alias)
	}
	sort.Strings(aliases)
	for _, alias := range aliases {
		fmt.Fprintf(&result, "%s %q\n", alias, used[alias])
	}
	result.WriteString(")\n\n")
	fmt.Fprintf(&result, "const %sModelFingerprint = %q\n\n", model, fmt.Sprintf("%x", digest))
	fmt.Fprintf(&result, "type %sColumns struct {\n", model)
	for _, field := range fields {
		fmt.Fprintf(&result, "%s %s.Column[%s,%s]\n", field.name, ormAlias, model, field.typ)
	}
	result.WriteString("}\n\n")
	fmt.Fprintf(&result, "func Check%sModel() error {\nt := %s.TypeOf((*%s)(nil)).Elem()\nif t.NumField() != %d { return %s.Errorf(\"ormgen: model field count drift; regenerate\") }\n", model, reflectAlias, model, fieldCount, fmtAlias)
	for _, field := range fields {
		fmt.Fprintf(&result, "{ f,ok := t.FieldByName(%q); if !ok || f.Type != %s.TypeOf((*%s)(nil)).Elem() || f.Tag.Get(\"db\") != %q { return %s.Errorf(\"ormgen: mapped field drift; regenerate\") } }\n", field.name, reflectAlias, field.typ, field.db, fmtAlias)
	}
	result.WriteString("return nil\n}\n\n")
	fmt.Fprintf(&result, "func New%sTable(schema,name string)(%s.Table[%s],%sColumns,error) {\nvar columns %sColumns\nvar zero %s.Table[%s]\nif err:=Check%sModel();err!=nil {return zero,columns,err}\ntable,err:=%s.NewTable[%s](schema,name)\nif err!=nil {return zero,columns,err}\n", model, ormAlias, model, model, model, ormAlias, model, model, ormAlias, model)
	for _, field := range fields {
		fmt.Fprintf(&result, "columns.%s,err=%s.NewColumn[%s,%s](table,%q)\nif err!=nil {return zero,%sColumns{},err}\n", field.name, ormAlias, model, field.typ, field.name, model)
	}
	result.WriteString("return table,columns,nil\n}\n")
	formatted, err := format.Source(result.Bytes())
	if err != nil {
		return nil, fmt.Errorf("ormgen: generated source formatting failed")
	}
	return formatted, nil
}

func validateType(value ast.Expr, imports, used map[string]string) error {
	switch typ := value.(type) {
	case *ast.IndexExpr:
		container, ok := typ.X.(*ast.SelectorExpr)
		if !ok || (container.Sel.Name != "Array" && container.Sel.Name != "Range" && container.Sel.Name != "SQLValue") {
			break
		}
		alias, ok := container.X.(*ast.Ident)
		if !ok || imports[alias.Name] != ormPath {
			break
		}
		element := typ.Index
		if container.Sel.Name == "SQLValue" {
			switch custom := element.(type) {
			case *ast.Ident:
				used[alias.Name] = ormPath
				return nil
			case *ast.SelectorExpr:
				qualifier, ok := custom.X.(*ast.Ident)
				if !ok {
					break
				}
				path := imports[qualifier.Name]
				if path == "" || qualifier.Name == "." || qualifier.Name == "_" {
					break
				}
				used[qualifier.Name] = path
				used[alias.Name] = ormPath
				return nil
			}
			break
		}
		if container.Sel.Name == "Range" {
			allowed := false
			switch bound := element.(type) {
			case *ast.Ident:
				allowed = bound.Name == "int32" || bound.Name == "int64"
			case *ast.SelectorExpr:
				if qualifier, ok := bound.X.(*ast.Ident); ok {
					path := imports[qualifier.Name]
					allowed = (path == "time" && bound.Sel.Name == "Time") || (path == ormPath && (bound.Sel.Name == "Decimal" || bound.Sel.Name == "Date"))
				}
			}
			if !allowed {
				break
			}
		}
		if pointer, ok := element.(*ast.StarExpr); ok {
			element = pointer.X
		}
		if _, nested := element.(*ast.IndexExpr); nested {
			break
		}
		if err := validateType(element, imports, used); err != nil {
			return err
		}
		used[alias.Name] = ormPath
		return nil
	case *ast.Ident:
		switch typ.Name {
		case "string", "bool", "int", "int32", "int64", "float32", "float64":
			return nil
		}
	case *ast.SelectorExpr:
		alias, ok := typ.X.(*ast.Ident)
		if !ok {
			break
		}
		path := imports[alias.Name]
		if (path == "time" && typ.Sel.Name == "Time") || (path == ormPath && (typ.Sel.Name == "Decimal" || typ.Sel.Name == "UUID" || typ.Sel.Name == "JSON" || typ.Sel.Name == "Bytea" || typ.Sel.Name == "Date" || typ.Sel.Name == "TimeOfDay" || typ.Sel.Name == "Interval" || typ.Sel.Name == "Enum" || typ.Sel.Name == "Inet" || typ.Sel.Name == "CIDR")) {
			used[alias.Name] = path
			return nil
		}
	}
	return fmt.Errorf("ormgen: scalar type outside qualified ORM codec profile")
}
