defmodule Neutron.OpenAPI do
  @moduledoc """
  OpenAPI 3.1 specification generator.

  Auto-generates an OpenAPI spec from registered router routes. Serves the spec
  at `/openapi.json` and an interactive Swagger UI at `/docs`.

  ## Usage

  Routes are automatically collected from your router module:

      spec = Neutron.OpenAPI.generate(MyApp.Router, title: "My API", version: "1.0.0")

  Or use as a Plug:

      forward "/openapi.json", to: Neutron.OpenAPI.JsonPlug, init_opts: [router: MyApp.Router]
      forward "/docs", to: Neutron.OpenAPI.DocsPlug, init_opts: [router: MyApp.Router]
  """

  @type spec :: map()

  @error_schema %{
    "type" => "object",
    "properties" => %{
      "type" => %{"type" => "string", "format" => "uri"},
      "title" => %{"type" => "string"},
      "status" => %{"type" => "integer"},
      "detail" => %{"type" => "string"},
      "instance" => %{"type" => "string"},
      "errors" => %{
        "type" => "array",
        "items" => %{
          "type" => "object",
          "properties" => %{
            "field" => %{"type" => "string"},
            "message" => %{"type" => "string"},
            "value" => %{}
          }
        }
      }
    },
    "required" => ["type", "title", "status", "detail"]
  }

  @doc """
  Generates an OpenAPI 3.1 specification from a router module.

  ## Options

    * `:title` — API title (default: "Neutron API")
    * `:version` — API version (default: from Neutron.version/0)
    * `:description` — API description
    * `:servers` — list of server URL maps
  """
  @spec generate(module(), keyword()) :: spec()
  def generate(router_module, opts \\ []) do
    title = Keyword.get(opts, :title, "Neutron API")
    version = Keyword.get(opts, :version, Neutron.version())
    description = Keyword.get(opts, :description, "Generated by Neutron framework")

    routes =
      if function_exported?(router_module, :__neutron_routes__, 0) do
        router_module.__neutron_routes__()
      else
        []
      end

    paths = build_paths(routes)

    %{
      "openapi" => "3.1.0",
      "info" => %{
        "title" => title,
        "version" => version,
        "description" => description
      },
      "servers" =>
        Keyword.get(opts, :servers, [
          %{"url" => "http://localhost:4000", "description" => "Local development"}
        ]),
      "paths" =>
        Map.merge(paths, %{
          "/health" => %{
            "get" => %{
              "summary" => "Health check",
              "operationId" => "getHealth",
              "tags" => ["system"],
              "responses" => %{
                "200" => %{
                  "description" => "Service is healthy",
                  "content" => %{
                    "application/json" => %{
                      "schema" => %{
                        "type" => "object",
                        "properties" => %{
                          "status" => %{"type" => "string", "enum" => ["ok"]},
                          "nucleus" => %{"type" => "boolean"},
                          "version" => %{"type" => "string"}
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }),
      "components" => %{
        "schemas" => %{
          "ProblemDetails" => @error_schema
        },
        "securitySchemes" => %{
          "bearerAuth" => %{
            "type" => "http",
            "scheme" => "bearer",
            "bearerFormat" => "JWT"
          }
        }
      }
    }
  end

  @doc """
  Encodes the spec as JSON.
  """
  @spec to_json(spec()) :: String.t()
  def to_json(spec) do
    Jason.encode!(spec, pretty: true)
  end

  defp build_paths(routes) do
    routes
    |> Enum.group_by(fn {_method, path, _opts} -> openapi_path(path) end)
    |> Enum.into(%{}, fn {path, methods} ->
      operations =
        Enum.into(methods, %{}, fn {method, _path, opts} ->
          {String.downcase(to_string(method)), build_operation(method, path, opts)}
        end)

      {path, operations}
    end)
  end

  defp build_operation(method, path, opts) do
    operation_id = Keyword.get(opts, :operation_id, generate_operation_id(method, path))
    summary = Keyword.get(opts, :summary, "#{method} #{path}")
    tags = Keyword.get(opts, :tags, [])

    op = %{
      "operationId" => operation_id,
      "summary" => summary,
      "responses" => %{
        "200" => %{"description" => "Successful response"},
        "400" => error_response("Bad Request"),
        "500" => error_response("Internal Server Error")
      }
    }

    op =
      if tags != [] do
        Map.put(op, "tags", tags)
      else
        op
      end

    # Add path parameters
    params = extract_path_params(path)

    if params != [] do
      Map.put(op, "parameters", params)
    else
      op
    end
  end

  defp error_response(description) do
    %{
      "description" => description,
      "content" => %{
        "application/problem+json" => %{
          "schema" => %{"$ref" => "#/components/schemas/ProblemDetails"}
        }
      }
    }
  end

  defp extract_path_params(path) do
    Regex.scan(~r/\{(\w+)\}/, path)
    |> Enum.map(fn [_, name] ->
      %{
        "name" => name,
        "in" => "path",
        "required" => true,
        "schema" => %{"type" => "string"}
      }
    end)
  end

  defp openapi_path(path) do
    # Convert :param to {param}
    String.replace(path, ~r/:(\w+)/, "{\\1}")
  end

  defp generate_operation_id(method, path) do
    clean =
      path
      |> String.replace(~r/[{}:\/]/, "_")
      |> String.replace(~r/_+/, "_")
      |> String.trim("_")

    "#{String.downcase(to_string(method))}_#{clean}"
  end
end

# =============================================================================
# OpenAPI JSON Plug
# =============================================================================
defmodule Neutron.OpenAPI.JsonPlug do
  @moduledoc "Serves the OpenAPI 3.1 spec as JSON at /openapi.json."
  @behaviour Plug

  @impl true
  def init(opts), do: opts

  @impl true
  def call(%{method: "GET"} = conn, opts) do
    router = Keyword.fetch!(opts, :router)
    spec = Neutron.OpenAPI.generate(router, opts)

    conn
    |> Plug.Conn.put_resp_content_type("application/json")
    |> Plug.Conn.send_resp(200, Neutron.OpenAPI.to_json(spec))
    |> Plug.Conn.halt()
  end

  def call(conn, _opts), do: conn
end

# =============================================================================
# Swagger UI Plug
# =============================================================================
defmodule Neutron.OpenAPI.DocsPlug do
  @moduledoc "Serves a Swagger UI page for interactive API exploration."
  @behaviour Plug

  @impl true
  def init(opts), do: opts

  @impl true
  def call(%{method: "GET"} = conn, _opts) do
    html = """
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <title>Neutron API Docs</title>
      <link rel="stylesheet" href="https://unpkg.com/swagger-ui-dist@5/swagger-ui.css">
    </head>
    <body>
      <div id="swagger-ui"></div>
      <script src="https://unpkg.com/swagger-ui-dist@5/swagger-ui-bundle.js"></script>
      <script>
        SwaggerUIBundle({url: '/openapi.json', dom_id: '#swagger-ui'});
      </script>
    </body>
    </html>
    """

    conn
    |> Plug.Conn.put_resp_content_type("text/html")
    |> Plug.Conn.send_resp(200, html)
    |> Plug.Conn.halt()
  end

  def call(conn, _opts), do: conn
end
