use serde::{Deserialize, Serialize};

/// Marker trait for typed IPC commands between frontend and backend.
///
/// Each command has a unique name and typed input/output. TypeScript bindings
/// are auto-generated at build time — no manual `invoke()` strings.
pub trait IpcCommand: Serialize + for<'de> Deserialize<'de> {
    /// The command name used for Tauri invoke routing.
    const NAME: &'static str;

    /// The return type of the command.
    type Output: Serialize + for<'de> Deserialize<'de>;
}

/// Generate a Tauri command handler from an IpcCommand implementation.
///
/// Usage:
/// ```ignore
/// #[derive(Serialize, Deserialize)]
/// struct GetUser { id: i64 }
///
/// impl IpcCommand for GetUser {
///     const NAME: &'static str = "get_user";
///     type Output = User;
/// }
/// ```
#[macro_export]
macro_rules! ipc_handler {
    ($cmd:ty, $handler:expr) => {
        #[tauri::command]
        async fn $cmd(input: $cmd) -> Result<<$cmd as IpcCommand>::Output, String> {
            ($handler)(input).await.map_err(|e| e.to_string())
        }
    };
}

/// TypeScript binding metadata for code generation.
#[derive(Debug, Serialize)]
pub struct TypeScriptBinding {
    pub command_name: String,
    pub input_type: String,
    pub output_type: String,
}

/// Collect all registered IPC command bindings for TypeScript codegen.
pub fn collect_bindings(bindings: &[TypeScriptBinding]) -> String {
    let mut output = String::from("// Auto-generated by neutron-desktop — do not edit\n");
    output.push_str("import { invoke } from '@tauri-apps/api/core';\n\n");

    for binding in bindings {
        output.push_str(&format!(
            "export async function {}(input: {}): Promise<{}> {{\n",
            to_camel_case(&binding.command_name),
            binding.input_type,
            binding.output_type,
        ));
        output.push_str(&format!(
            "    return invoke('{}', {{ input }});\n",
            binding.command_name
        ));
        output.push_str("}\n\n");
    }

    output
}

fn to_camel_case(s: &str) -> String {
    let mut result = String::new();
    let mut capitalize_next = false;
    for (i, c) in s.chars().enumerate() {
        if c == '_' {
            capitalize_next = true;
        } else if capitalize_next || (i == 0) {
            if i == 0 {
                result.push(c.to_ascii_lowercase());
            } else {
                result.push(c.to_ascii_uppercase());
            }
            capitalize_next = false;
        } else {
            result.push(c);
        }
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_to_camel_case() {
        assert_eq!(to_camel_case("get_user"), "getUser");
        assert_eq!(to_camel_case("show_file_dialog"), "showFileDialog");
        assert_eq!(to_camel_case("list"), "list");
    }

    #[test]
    fn test_collect_bindings() {
        let bindings = vec![TypeScriptBinding {
            command_name: "get_user".to_string(),
            input_type: "{ id: number }".to_string(),
            output_type: "User".to_string(),
        }];
        let output = collect_bindings(&bindings);
        assert!(output.contains("export async function getUser"));
        assert!(output.contains("invoke('get_user'"));
    }
}
