defmodule Neutron.OpenAPITest do
  use ExUnit.Case, async: true
  use Plug.Test

  alias Neutron.OpenAPI

  defmodule TestRouter do
    def __neutron_routes__ do
      [
        {:GET, "/users", [summary: "List users", tags: ["users"]]},
        {:POST, "/users", [summary: "Create user", tags: ["users"]]},
        {:GET, "/users/:id", [summary: "Get user", tags: ["users"]]},
        {:DELETE, "/users/:id", [summary: "Delete user"]},
        {:GET, "/health", []}
      ]
    end
  end

  defmodule EmptyRouter do
    def __neutron_routes__, do: []
  end

  defmodule NoRoutesRouter do
    # Does not export __neutron_routes__
  end

  describe "generate/2" do
    test "produces a valid OpenAPI 3.1 spec" do
      spec = OpenAPI.generate(TestRouter)
      assert spec["openapi"] == "3.1.0"
    end

    test "includes info section with defaults" do
      spec = OpenAPI.generate(TestRouter)
      assert spec["info"]["title"] == "Neutron API"
      assert spec["info"]["version"] == Neutron.version()
      assert spec["info"]["description"] == "Generated by Neutron framework"
    end

    test "accepts custom title and version" do
      spec = OpenAPI.generate(TestRouter, title: "My API", version: "2.0.0")
      assert spec["info"]["title"] == "My API"
      assert spec["info"]["version"] == "2.0.0"
    end

    test "accepts custom description" do
      spec = OpenAPI.generate(TestRouter, description: "Custom desc")
      assert spec["info"]["description"] == "Custom desc"
    end

    test "includes /health path" do
      spec = OpenAPI.generate(TestRouter)
      assert Map.has_key?(spec["paths"], "/health")
      assert spec["paths"]["/health"]["get"]["summary"] == "Health check"
    end

    test "converts :param to {param} in OpenAPI paths" do
      spec = OpenAPI.generate(TestRouter)
      assert Map.has_key?(spec["paths"], "/users/{id}")
    end

    test "includes path parameters" do
      spec = OpenAPI.generate(TestRouter)
      get_user = spec["paths"]["/users/{id}"]["get"]
      assert is_list(get_user["parameters"])
      param = hd(get_user["parameters"])
      assert param["name"] == "id"
      assert param["in"] == "path"
      assert param["required"] == true
    end

    test "includes tags from route options" do
      spec = OpenAPI.generate(TestRouter)
      get_users = spec["paths"]["/users"]["get"]
      assert get_users["tags"] == ["users"]
    end

    test "includes summaries from route options" do
      spec = OpenAPI.generate(TestRouter)
      get_users = spec["paths"]["/users"]["get"]
      assert get_users["summary"] == "List users"
    end

    test "includes default servers" do
      spec = OpenAPI.generate(TestRouter)
      assert is_list(spec["servers"])
      assert length(spec["servers"]) > 0
      assert hd(spec["servers"])["url"] == "http://localhost:4000"
    end

    test "accepts custom servers" do
      spec = OpenAPI.generate(TestRouter,
        servers: [%{"url" => "https://api.example.com"}]
      )
      assert hd(spec["servers"])["url"] == "https://api.example.com"
    end

    test "includes components with ProblemDetails schema" do
      spec = OpenAPI.generate(TestRouter)
      assert Map.has_key?(spec["components"]["schemas"], "ProblemDetails")
    end

    test "includes bearerAuth security scheme" do
      spec = OpenAPI.generate(TestRouter)
      bearer = spec["components"]["securitySchemes"]["bearerAuth"]
      assert bearer["type"] == "http"
      assert bearer["scheme"] == "bearer"
      assert bearer["bearerFormat"] == "JWT"
    end

    test "includes response schemas for errors" do
      spec = OpenAPI.generate(TestRouter)
      get_users = spec["paths"]["/users"]["get"]
      assert Map.has_key?(get_users["responses"], "400")
      assert Map.has_key?(get_users["responses"], "500")
    end

    test "handles empty router" do
      spec = OpenAPI.generate(EmptyRouter)
      # Should still have /health
      assert Map.has_key?(spec["paths"], "/health")
    end

    test "handles router without __neutron_routes__" do
      spec = OpenAPI.generate(NoRoutesRouter)
      assert Map.has_key?(spec["paths"], "/health")
    end
  end

  describe "to_json/1" do
    test "encodes spec as JSON string" do
      spec = OpenAPI.generate(TestRouter)
      json = OpenAPI.to_json(spec)
      assert is_binary(json)
      assert {:ok, _} = Jason.decode(json)
    end

    test "JSON is pretty-printed" do
      spec = OpenAPI.generate(TestRouter)
      json = OpenAPI.to_json(spec)
      # Pretty-printed JSON contains newlines
      assert json =~ "\n"
    end
  end

  describe "Neutron.OpenAPI.JsonPlug" do
    test "serves OpenAPI spec as JSON on GET" do
      opts = Neutron.OpenAPI.JsonPlug.init(router: TestRouter)

      conn =
        conn(:get, "/openapi.json")
        |> Neutron.OpenAPI.JsonPlug.call(opts)

      assert conn.status == 200
      assert conn.halted

      content_type = get_resp_header(conn, "content-type") |> List.first()
      assert content_type =~ "application/json"

      body = Jason.decode!(conn.resp_body)
      assert body["openapi"] == "3.1.0"
    end

    test "passes through non-GET requests" do
      opts = Neutron.OpenAPI.JsonPlug.init(router: TestRouter)

      conn =
        conn(:post, "/openapi.json")
        |> Neutron.OpenAPI.JsonPlug.call(opts)

      refute conn.halted
    end
  end

  describe "Neutron.OpenAPI.DocsPlug" do
    test "serves Swagger UI HTML on GET" do
      opts = Neutron.OpenAPI.DocsPlug.init(router: TestRouter)

      conn =
        conn(:get, "/docs")
        |> Neutron.OpenAPI.DocsPlug.call(opts)

      assert conn.status == 200
      assert conn.halted

      content_type = get_resp_header(conn, "content-type") |> List.first()
      assert content_type =~ "text/html"

      assert conn.resp_body =~ "swagger-ui"
      assert conn.resp_body =~ "/openapi.json"
    end

    test "passes through non-GET requests" do
      opts = Neutron.OpenAPI.DocsPlug.init(router: TestRouter)

      conn =
        conn(:post, "/docs")
        |> Neutron.OpenAPI.DocsPlug.call(opts)

      refute conn.halted
    end
  end
end
