-- boolean logic, NULL-safe comparison, conditional expressions
SELECT true AND NULL, false AND NULL, true OR NULL, false OR NULL, NOT NULL;
SELECT NULL = NULL, NULL <> NULL, NULL IS NULL, NULL IS NOT NULL;
SELECT 1 IS DISTINCT FROM 1, 1 IS DISTINCT FROM 2, 1 IS DISTINCT FROM NULL, NULL IS DISTINCT FROM NULL;
SELECT 1 IS NOT DISTINCT FROM NULL, NULL IS NOT DISTINCT FROM NULL;
SELECT true IS TRUE, false IS TRUE, NULL IS TRUE, NULL IS NOT TRUE;
SELECT true IS FALSE, NULL IS FALSE, NULL IS NOT FALSE;
SELECT true IS UNKNOWN, NULL IS UNKNOWN, NULL IS NOT UNKNOWN;
-- BETWEEN and its symmetric form
SELECT 5 BETWEEN 1 AND 10, 5 BETWEEN 10 AND 1;
-- BETWEEN SYMMETRIC is a documented deviation; see known_deviations.sql
SELECT 5 NOT BETWEEN 1 AND 10, NULL BETWEEN 1 AND 10;
-- IN with and without NULL
SELECT 1 IN (1, 2), 3 IN (1, 2), 3 IN (1, NULL), 1 IN (1, NULL);
SELECT 3 NOT IN (1, 2), 3 NOT IN (1, NULL);
-- COALESCE / NULLIF / GREATEST / LEAST
SELECT COALESCE(NULL, NULL, 3), COALESCE(NULL::int, NULL), NULLIF(1, 1), NULLIF(1, 2);
SELECT GREATEST(1, 2, 3), LEAST(1, 2, 3), GREATEST(1, NULL, 3), LEAST(NULL, 2);
-- CASE with NULLs and type mixing
SELECT CASE WHEN NULL THEN 'a' ELSE 'b' END;
SELECT CASE WHEN true THEN NULL ELSE 'b' END;
SELECT CASE 1 WHEN NULL THEN 'null-match' WHEN 1 THEN 'one' ELSE 'other' END;
-- comparison chains over a table, including WHERE on a NULL column
CREATE TABLE bc_t (id INT, b BOOLEAN, n INT);
INSERT INTO bc_t VALUES (1, true, 1), (2, false, NULL), (3, NULL, 3);
SELECT id FROM bc_t WHERE b ORDER BY id;
SELECT id FROM bc_t WHERE NOT b ORDER BY id;
SELECT id FROM bc_t WHERE b IS NOT TRUE ORDER BY id;
SELECT id FROM bc_t WHERE n IS DISTINCT FROM 1 ORDER BY id;
SELECT id FROM bc_t WHERE n <> 1 ORDER BY id;
SELECT count(*) FROM bc_t WHERE n = NULL;
DROP TABLE bc_t;
