/**
 * File-based route discovery.
 *
 * At build time (Re.Pack + Rspack), a babel transform walks the `app/`
 * directory and generates a static route manifest. At runtime we consume
 * that manifest here.
 *
 * Convention (same as Neutron TS web router):
 *   app/index.tsx          → /
 *   app/about.tsx          → /about
 *   app/user/[id].tsx      → /user/:id
 *   app/(tabs)/_layout.tsx → (tabs) group layout
 *   app/(tabs)/home.tsx    → /home inside tabs group
 *   app/_layout.tsx        → root layout (wraps all routes)
 *   app/+not-found.tsx     → 404 screen
 */

import type { RouteRecord } from './types.js'
import type { ComponentType, ReactNode } from 'react'
import { lazyRoute } from './lazy-route.js'

export interface RouteManifestEntry {
  path: string
  segment: string
  dynamic: boolean
  group: boolean
  layout: boolean
  notFound: boolean
}

export type RouteComponent = { kind: 'component'; component: ComponentType } | { kind: 'lazy'; load: () => Promise<{ default: ComponentType }>; loading?: ReactNode; errorFallback?: (error: Error) => ReactNode }

/** Generated by the build-time transform. Apps import this from .neutron/routes.ts */
export interface RouteManifest {
  entries: RouteManifestEntry[]
}

/**
 * Build a RouteRecord tree from a manifest + lazy component map.
 *
 * @param manifest   - Generated route manifest
 * @param components - Map of route path → component (lazy loaded)
 */
export function buildRouteTree(
  manifest: RouteManifest,
  components: Record<string, ComponentType | RouteComponent>,
): RouteRecord[] {
  const tree: RouteRecord[] = []
  const byPath = new Map<string, RouteRecord>()

  // Sort by depth so parents are processed before children
  const sorted = [...manifest.entries].sort(
    (a, b) => a.path.split('/').length - b.path.split('/').length,
  )

  for (const entry of sorted) {
    const source = components[entry.path]
    const comp = typeof source === 'function' ? source
      : source?.kind === 'lazy' ? lazyRoute(source.load, source.loading, source.errorFallback)
      : source?.kind === 'component' ? source.component : undefined
    const record: RouteRecord = {
      segment: entry.segment,
      dynamic: entry.dynamic,
      group: entry.group,
      component: comp,
    }

    if (entry.layout) {
      record.layout = comp as ComponentType<{ children: ReactNode }>
    }

    const parentPath = entry.path.includes('/')
      ? entry.path.slice(0, entry.path.lastIndexOf('/'))
      : ''

    if (parentPath && byPath.has(parentPath)) {
      const parent = byPath.get(parentPath)!
      parent.children = parent.children ?? []
      parent.children.push(record)
    } else {
      tree.push(record)
    }

    byPath.set(entry.path, record)
  }

  return tree
}

/**
 * Match a pathname against a route tree.
 * Returns the matched record and extracted params, or null if no match.
 */
export function matchRoute(
  segments: string[],
  tree: RouteRecord[],
  params: Record<string, string> = {},
): { record: RouteRecord; params: Record<string, string> } | null {
  const [current, ...rest] = segments

  for (const record of [...tree].sort((a, b) => Number(a.dynamic) - Number(b.dynamic))) {
    if (record.group) {
      // Groups are transparent — recurse without consuming a segment
      const match = matchRoute(segments, record.children ?? [], params)
      if (match) return match
      continue
    }

    if (record.dynamic && current !== undefined) {
      const paramName = record.segment.replace(/^\[|\]$/g, '')
      const newParams = { ...params, [paramName]: current }
      if (rest.length === 0 && record.component) {
        return { record, params: newParams }
      }
      const match = matchRoute(rest, record.children ?? [], newParams)
      if (match) return match
    } else if (record.segment === current || (current === undefined && record.segment === 'index')) {
      if (rest.length === 0) {
        return { record, params }
      }
      const match = matchRoute(rest, record.children ?? [], params)
      if (match) return match
    }
  }

  return null
}
