// Auto-generated by Neutron. Do not edit.
declare module "neutron" {
  interface NeutronGeneratedRouteMap {
    paths:
    | "/"
    | "/about"
    | "/blog"
    | `/blog/${string}`
    | "/users"
  }
}

export {};
