[package]
name = "neutron-desktop-biometrics"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Neutron Desktop TouchID / Windows Hello biometrics plugin"

[dependencies]
tauri = { workspace = true }
tauri-plugin = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
whoami = "1"

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6.2"
objc2-foundation = "0.3.2"
objc2-local-authentication = "0.3.2"
block2 = "0.6.2"
