package studio

import (
	"context"
	"log"
	"net/http"
	"sort"
	"strings"

	"github.com/neutron-build/neutron/cli/internal/db"
)

// Row-level table introspection shared by every v2 mutation (rows_v2.go,
// commit_v2.go), plus the FK map that powers "follow reference"
// navigation. All identifiers are quoted; all values are bound parameters.
// The pre-S01 single-column-key endpoints (/api/table/update and
// /api/table/delete) are retired: the SPA uses the full-key v2 protocol.

// tableColumnMeta is one introspected column of a table.
type tableColumnMeta struct {
	Name        string
	IsPK        bool
	Identity    string // attidentity: '' | 'a' (always) | 'd' (by default)
	Generated   string // attgenerated: '' | 's' (stored)
	DefaultExpr string
	TypeOID     uint32 // pg_type.oid — drives the wire tag
	TypeName    string // pg_type.typname
	TypType     string // pg_type.typtype: 'b' base, 'e' enum, 'd' domain, ...
	NotNull     bool
	KeyPos      int  // 1-based position in the primary key, 0 when not a key column
	CanUpdate   bool // has_column_privilege(..., 'UPDATE') for the current role
	CanInsert   bool // has_column_privilege(..., 'INSERT') for the current role
	Attnum      int  // pg_attribute.attnum — addresses the column in catalog tuples (e.g. FK confkey)
}

// autoAssigned reports whether the column's value is generated by the server
// (identity, stored generated, or a nextval/serial default).
func (m tableColumnMeta) autoAssigned() bool {
	return m.Identity != "" || m.Generated != "" ||
		strings.HasPrefix(strings.ToLower(m.DefaultExpr), "nextval(")
}

// tableMeta is the authoritative, freshly introspected shape of a table.
type tableMeta struct {
	Exists    bool
	RelOID    uint32   // pg_class.oid: binds identities to this exact relation
	PKCols    []string // primary-key columns in constraint (index key) order
	Columns   map[string]tableColumnMeta
	Order     []tableColumnMeta // attnum order (map iteration is random)
	CanDelete bool              // has_table_privilege(..., 'DELETE')
	// ForeignDescendant: an inheritance descendant is a foreign table. Its
	// rows carry no local xmin (always 0) and a remote ctid, so neither the
	// version check nor the tuple binding can guard a write to them.
	ForeignDescendant bool
	// RuleEvents holds the pg_rewrite ev_type of each write whose Studio
	// statement a rule makes PostgreSQL refuse ('2' UPDATE, '3' INSERT,
	// '4' DELETE); see ruleRefusal. Only rules that fire count (enabled,
	// or replica-only under session_replication_role = replica).
	RuleEvents string
}

// tableMetaSQL reads the table's columns, primary-key membership and key
// position, type, generated/identity/default flags and the current role's
// privileges from pg_catalog. Studio-owned introspection (kept here rather
// than in internal/db): mutations must re-verify key metadata at request
// time, independent of what the browser claims. Only a valid primary index
// is a key: an invalid one (ALTER TABLE ONLY ... ADD PRIMARY KEY on a
// partitioned table) enforces no uniqueness, so it cannot identify a row.
const tableMetaSQL = `
SELECT a.attname,
       COALESCE((
	       SELECT u.ord
	       FROM pg_catalog.pg_index i
	       CROSS JOIN LATERAL pg_catalog.unnest(i.indkey) WITH ORDINALITY AS u(k, ord)
	       WHERE i.indrelid = c.oid AND i.indisprimary AND i.indisvalid AND u.k = a.attnum
       ), 0) AS key_pos,
       COALESCE(a.attidentity::text, ''),
       COALESCE(a.attgenerated::text, ''),
       COALESCE(pg_catalog.pg_get_expr(d.adbin, d.adrelid), ''),
       a.atttypid,
       t.typname,
       t.typtype::text,
       a.attnotnull,
       c.oid,
       pg_catalog.has_column_privilege(c.oid, a.attnum, 'UPDATE'),
       pg_catalog.has_column_privilege(c.oid, a.attnum, 'INSERT'),
       pg_catalog.has_table_privilege(c.oid, 'DELETE'),
       a.attnum,
       EXISTS (
	       WITH RECURSIVE d(oid) AS (
		       SELECT inhrelid FROM pg_catalog.pg_inherits WHERE inhparent = c.oid
		       UNION
		       SELECT i.inhrelid FROM pg_catalog.pg_inherits i JOIN d ON i.inhparent = d.oid
	       )
	       SELECT 1 FROM d JOIN pg_catalog.pg_class k ON k.oid = d.oid WHERE k.relkind = 'f'
       ),
       COALESCE((
	       SELECT pg_catalog.string_agg(DISTINCT r.ev_type::text, '')
	       FROM pg_catalog.pg_rewrite r
	       WHERE r.ev_class = c.oid AND r.ev_type IN ('2','3','4')
	         AND r.ev_enabled::text IN ('A', CASE pg_catalog.current_setting('session_replication_role')
	                                         WHEN 'replica' THEN 'R' ELSE 'O' END)
	         AND (r.ev_type <> '3' OR r.is_instead)
       ), '')
FROM pg_catalog.pg_class c
JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
JOIN pg_catalog.pg_attribute a ON a.attrelid = c.oid AND a.attnum > 0 AND NOT a.attisdropped
JOIN pg_catalog.pg_type t ON t.oid = a.atttypid
LEFT JOIN pg_catalog.pg_attrdef d ON d.adrelid = c.oid AND d.adnum = a.attnum
WHERE n.nspname = $1 AND c.relname = $2 AND c.relkind IN ('r','p')
ORDER BY a.attnum
`

// fetchTableMeta re-introspects a table from the database. Zero columns means
// the relation does not exist (or is not an ordinary table).
func fetchTableMeta(ctx context.Context, client *db.Client, schemaName, tableName string) (*tableMeta, error) {
	rows, err := client.Query(ctx, tableMetaSQL, schemaName, tableName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	meta := &tableMeta{Columns: map[string]tableColumnMeta{}}
	var keyed []tableColumnMeta
	for rows.Next() {
		var col tableColumnMeta
		var keyPos int32
		if err := rows.Scan(&col.Name, &keyPos, &col.Identity, &col.Generated, &col.DefaultExpr,
			&col.TypeOID, &col.TypeName, &col.TypType, &col.NotNull,
			&meta.RelOID, &col.CanUpdate, &col.CanInsert, &meta.CanDelete, &col.Attnum, &meta.ForeignDescendant, &meta.RuleEvents); err != nil {
			return nil, err
		}
		col.KeyPos = int(keyPos)
		col.IsPK = col.KeyPos > 0
		meta.Columns[col.Name] = col
		meta.Order = append(meta.Order, col)
		if col.IsPK {
			keyed = append(keyed, col)
		}
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	sort.Slice(keyed, func(i, j int) bool { return keyed[i].KeyPos < keyed[j].KeyPos })
	for _, col := range keyed {
		meta.PKCols = append(meta.PKCols, col.Name)
	}
	meta.Exists = len(meta.Columns) > 0
	return meta, nil
}

// fkDetail describes one foreign key constraint with its COMPLETE key
// tuples: composite FKs carry every (column, refColumn) pair in constraint
// order, so FK navigation and editing address the whole tuple, never one
// component. Single-column FKs additionally expose the legacy per-column
// fields for existing consumers.
type fkDetail struct {
	Name       string   `json:"name"`
	Columns    []string `json:"columns"`
	RefSchema  string   `json:"refSchema"`
	RefTable   string   `json:"refTable"`
	RefColumns []string `json:"refColumns"`
	Composite  bool     `json:"composite"`
	// Legacy per-column spelling, set only when len(Columns) == 1.
	Column    string `json:"column,omitempty"`
	RefColumn string `json:"refColumn,omitempty"`
}

func (s *Server) handleTableFKs(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		writeError(w, http.StatusMethodNotAllowed, "method not allowed")
		return
	}
	q := r.URL.Query()
	connID := q.Get("connectionId")
	schemaName := q.Get("schema")
	tableName := q.Get("table")
	if connID == "" || schemaName == "" || tableName == "" {
		writeError(w, http.StatusBadRequest, "connectionId, schema, and table are required")
		return
	}
	client, ok := s.clientFor(connID)
	if !ok {
		writeError(w, http.StatusBadRequest, "not connected")
		return
	}

	fks, err := tableForeignKeys(r.Context(), client, schemaName, tableName)
	if err != nil {
		log.Printf("studio: fk query error: %v", err)
		writeJSON(w, http.StatusOK, map[string]any{"fks": []fkDetail{}, "error": sanitizeError(err)})
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{"fks": fks})
}

func tableForeignKeys(ctx context.Context, client *db.Client, schemaName, tableName string) ([]fkDetail, error) {
	// One row per constraint; the LATERAL unnest keeps conkey/confkey pairs
	// aligned (pair i of the local tuple maps to pair i of the target tuple)
	// and array_agg preserves the in-constraint order.
	const fkSQL = `
SELECT rc.conname,
       nf.nspname AS refschema,
       rt.relname AS reftable,
       array_agg(fa.attname ORDER BY k.ord) AS concols,
       array_agg(ta.attname ORDER BY k.ord) AS refcols
FROM pg_constraint rc
JOIN pg_class cl ON cl.oid = rc.conrelid
JOIN pg_namespace n ON n.oid = cl.relnamespace AND n.nspname = $1
JOIN pg_class rt ON rt.oid = rc.confrelid
JOIN pg_namespace nf ON nf.oid = rt.relnamespace
CROSS JOIN LATERAL unnest(rc.conkey, rc.confkey) WITH ORDINALITY AS k(cnum, rnum, ord)
JOIN pg_attribute fa ON fa.attrelid = cl.oid AND fa.attnum = k.cnum
JOIN pg_attribute ta ON ta.attrelid = rt.oid AND ta.attnum = k.rnum
WHERE rc.contype = 'f' AND cl.relname = $2
GROUP BY rc.conname, nf.nspname, rt.relname, rc.oid
ORDER BY rc.conname
`
	rows, err := client.Query(ctx, fkSQL, schemaName, tableName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var fks []fkDetail
	for rows.Next() {
		var fk fkDetail
		if err := rows.Scan(&fk.Name, &fk.RefSchema, &fk.RefTable, &fk.Columns, &fk.RefColumns); err != nil {
			return nil, err
		}
		fk.Composite = len(fk.Columns) > 1
		if !fk.Composite {
			fk.Column = fk.Columns[0]
			fk.RefColumn = fk.RefColumns[0]
		}
		fks = append(fks, fk)
	}
	return fks, rows.Err()
}
