import * as fs from "node:fs/promises";
import * as path from "node:path";
import { discoverRoutes } from "./manifest.js";
import type { Route } from "./types.js";

export interface PrepareRouteTypesOptions {
  rootDir?: string;
  routesDir?: string;
  writeTypes?: boolean;
  typesPath?: string;
}

const ROUTE_TYPES_FILE_NAME = ".neutron-routes.d.ts";

export async function prepareRouteTypes(
  options: PrepareRouteTypesOptions = {}
): Promise<void> {
  const rootDir = path.resolve(options.rootDir || process.cwd());
  const routesDir = path.resolve(rootDir, options.routesDir || "src/routes");
  const writeTypes = options.writeTypes !== false;
  if (!writeTypes) {
    return;
  }

  const routes = discoverRoutes({ routesDir }).filter(
    (route) => !route.file.includes("_layout")
  );
  const declaration = generateRouteTypesDeclaration(routes);

  const outputPath =
    options.typesPath || path.join(routesDir, ROUTE_TYPES_FILE_NAME);
  await fs.mkdir(path.dirname(outputPath), { recursive: true });
  await fs.writeFile(outputPath, declaration, "utf-8");
}

export function generateRouteTypesDeclaration(routes: Route[]): string {
  const routePaths = [...new Set(routes.map((route) => route.path))].sort();
  const typeLines = routePaths.map((routePath) => `    | ${toPathType(routePath)}`);

  const pathUnion =
    typeLines.length > 0
      ? ["  interface NeutronGeneratedRouteMap {", "    paths:", ...typeLines, "  }"]
      : ['  interface NeutronGeneratedRouteMap {', '    paths: never', "  }"];

  return [
    "// Auto-generated by Neutron. Do not edit.",
    'declare module "neutron" {',
    ...pathUnion,
    "}",
    "",
    "export {};",
    "",
  ].join("\n");
}

function toPathType(routePath: string): string {
  if (routePath === "/") {
    return '"/"';
  }

  const segments = routePath.split("/").filter(Boolean);
  let pattern = "";
  let hasDynamicSegment = false;

  for (const segment of segments) {
    pattern += "/";
    if (segment.startsWith(":") || segment === "*") {
      pattern += "${string}";
      hasDynamicSegment = true;
      continue;
    }
    pattern += escapeTemplateSegment(segment);
  }

  if (!hasDynamicSegment) {
    return `"${pattern}"`;
  }

  return `\`${pattern}\``;
}

function escapeTemplateSegment(segment: string): string {
  return segment.replace(/[`$\\]/g, (token) => `\\${token}`);
}
