package orm

import (
	"context"
	"errors"
	"fmt"
	"os"
	"reflect"
	"testing"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
)

// Live PostgreSQL uses an owned temporary schema, native pgx oracles and the
// caller's default pgx extended/cached protocol. No Nucleus profile is implied.
func TestPostgresCore(t *testing.T) {
	url := os.Getenv("NEUTRON_ORM_TEST_DATABASE_URL")
	if url == "" {
		if os.Getenv("NEUTRON_ORM_REQUIRE_LIVE") == "1" {
			t.Fatal("NEUTRON_ORM_TEST_DATABASE_URL required")
		}
		t.Skip("set NEUTRON_ORM_TEST_DATABASE_URL for actual PostgreSQL verification")
	}
	ctx, cancel := context.WithTimeout(context.Background(), 45*time.Second)
	defer cancel()
	conn, err := pgx.Connect(ctx, url)
	if err != nil {
		t.Fatal("PostgreSQL connection failed")
	}
	t.Cleanup(func() {
		closeCtx, done := context.WithTimeout(context.Background(), 10*time.Second)
		defer done()
		if err := conn.Close(closeCtx); err != nil {
			t.Error("connection close failed")
		}
	})
	if conn.Config().DefaultQueryExecMode == pgx.QueryExecModeSimpleProtocol {
		t.Fatal("live profile must verify native pgx default protocol")
	}
	schema := fmt.Sprintf("orm_core_%d", time.Now().UnixNano())
	shadow := schema + "_shadow"
	_, err = conn.Exec(ctx, "CREATE SCHEMA "+quote(schema)+"; CREATE SCHEMA "+quote(shadow))
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() {
		clean, done := context.WithTimeout(context.Background(), 10*time.Second)
		defer done()
		if _, err := conn.Exec(clean, "DROP SCHEMA "+quote(schema)+" CASCADE; DROP SCHEMA "+quote(shadow)+" CASCADE"); err != nil {
			t.Error("owned schema cleanup failed")
		}
	})
	ddl := ` (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tenant text NOT NULL DEFAULT 'tenant-default', active boolean NOT NULL DEFAULT true, score bigint NOT NULL DEFAULT 99, name text NOT NULL DEFAULT 'server', note text DEFAULT 'note-default', UNIQUE(tenant,name))`
	if _, err := conn.Exec(ctx, "CREATE TABLE "+quote(schema)+`.records`+ddl+"; CREATE TABLE "+quote(shadow)+`.records`+ddl); err != nil {
		t.Fatal(err)
	}
	if _, err := conn.Exec(ctx, "INSERT INTO "+quote(shadow)+`.records (tenant,name) VALUES ('shadow','shadow'); SET search_path TO `+quote(shadow)); err != nil {
		t.Fatal(err)
	}
	table, err := NewTable[testModel](schema, "records")
	if err != nil {
		t.Fatal(err)
	}
	id, _ := NewColumn[testModel, int64](table, "ID")
	tenant, _ := NewColumn[testModel, string](table, "Tenant")
	active, _ := NewColumn[testModel, bool](table, "Active")
	score, _ := NewColumn[testModel, int64](table, "Score")
	name, _ := NewColumn[testModel, string](table, "Name")
	note, _ := NewColumn[testModel, *string](table, "Note")
	first, err := InsertOne(ctx, conn, table, Set(tenant, Some("owner")), Set(active, Some(false)), Set(score, Some(int64(0))), Set(name, Some("")), Set(note, Some((*string)(nil))))
	if err != nil {
		t.Fatal(err)
	}
	if first.ID == 0 || first.Active || first.Score != 0 || first.Name != "" || first.Note != nil {
		t.Fatal(first)
	}
	// Independent native oracle does not call the ORM scanner or compiler.
	var nativeActive bool
	var nativeScore int64
	var nativeName string
	var nativeNote *string
	err = conn.QueryRow(ctx, "SELECT active,score,name,note FROM "+quote(schema)+".records WHERE id=$1", first.ID).Scan(&nativeActive, &nativeScore, &nativeName, &nativeNote)
	if err != nil || nativeActive || nativeScore != 0 || nativeName != "" || nativeNote != nil {
		t.Fatal("native value mismatch", err)
	}
	second, err := InsertOne(ctx, conn, table, Set(tenant, Some("other")), Set(name, Default[string]()), Set(note, Omit[*string]()))
	if err != nil || !second.Active || second.Score != 99 || second.Name != "server" || second.Note == nil || *second.Note != "note-default" {
		t.Fatal(second, err)
	}
	rows, err := Select(ctx, conn, table, Query[testModel]{}.OrderBy(id.Asc()))
	if err != nil || len(rows) != 2 {
		t.Fatal(rows, err)
	}
	names, err := SelectColumn(ctx, conn, name, Query[testModel]{}.Where(tenant.Eq("other")))
	if err != nil || !reflect.DeepEqual(names, []string{"server"}) {
		t.Fatal(names, err)
	}
	pairs, err := SelectPair(ctx, conn, id, note, Query[testModel]{}.Where(tenant.Eq("owner")))
	if err != nil || len(pairs) != 1 || pairs[0].First != first.ID || pairs[0].Second != nil {
		t.Fatal(pairs, err)
	}
	if _, err := SelectOne(ctx, conn, table, Query[testModel]{}); !errors.Is(err, ErrCardinality) {
		t.Fatal("multiple rows did not fail", err)
	}
	if _, err := SelectOne(ctx, conn, table, Query[testModel]{}.Where(id.Eq(-1))); !errors.Is(err, ErrNotFound) {
		t.Fatal("missing row did not fail", err)
	}
	if _, err := SelectOne(ctx, conn, table, Query[testModel]{}.Limit(1)); err == nil {
		t.Fatal("limiting hid cardinality")
	}
	n, err := Update(ctx, conn, table, And(id.Eq(first.ID), tenant.Eq("other")), Set(name, Some("wrong")))
	if err != nil || n != 0 {
		t.Fatal(n, err)
	}
	if err := conn.QueryRow(ctx, "SELECT name FROM "+quote(schema)+".records WHERE id=$1", first.ID).Scan(&nativeName); err != nil || nativeName != "" {
		t.Fatal("foreign-tenant update changed native row", err)
	}
	n, err = Update(ctx, conn, table, And(id.Eq(first.ID), tenant.Eq("owner")), Set(name, Default[string]()), Set(note, Some((*string)(nil))))
	if err != nil || n != 1 {
		t.Fatal(n, err)
	}
	updated, err := SelectOne(ctx, conn, table, Query[testModel]{}.Where(id.Eq(first.ID)))
	if err != nil || updated.Name != "server" || updated.Note != nil {
		t.Fatal(updated, err)
	}
	if err := conn.QueryRow(ctx, "SELECT name,note FROM "+quote(schema)+".records WHERE id=$1", first.ID).Scan(&nativeName, &nativeNote); err != nil || nativeName != "server" || nativeNote != nil {
		t.Fatal("default/NULL native update mismatch", err)
	}
	if _, err := Update(ctx, conn, table, Predicate[testModel]{}, Set(name, Some("unscoped"))); err == nil {
		t.Fatal("unscoped write accepted")
	}
	if _, err := InsertOne(ctx, conn, table, Set(tenant, Some("owner")), Set(name, Some("server"))); err == nil {
		t.Fatal("unique violation absent")
	} else {
		var p *pgconn.PgError
		if !errors.As(err, &p) || p.Code != "23505" {
			t.Fatal("SQLSTATE lost", err)
		}
	}
	// A BEFORE INSERT trigger may suppress the tuple without raising a server
	// error. The single-row helper must report cardinality rather than success.
	trigger := "CREATE FUNCTION " + quote(schema) + `.suppress_insert() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.name='suppress' THEN RETURN NULL; END IF; RETURN NEW; END $$; CREATE TRIGGER suppress_insert BEFORE INSERT ON ` + quote(schema) + `.records FOR EACH ROW EXECUTE FUNCTION ` + quote(schema) + `.suppress_insert()`
	if _, err := conn.Exec(ctx, trigger); err != nil {
		t.Fatal(err)
	}
	if _, err := InsertOne(ctx, conn, table, Set(tenant, Some("owner")), Set(name, Some("suppress"))); !errors.Is(err, ErrCardinality) {
		t.Fatal("suppressed insert cardinality", err)
	}
	var suppressed int
	if err := conn.QueryRow(ctx, "SELECT count(*) FROM "+quote(schema)+".records WHERE name='suppress'").Scan(&suppressed); err != nil || suppressed != 0 {
		t.Fatal("suppressed native insert", err)
	}
	// A deliberately incompatible return codec establishes an important
	// borrowed-autocommit boundary: scan failure does not roll back insertion.
	if _, err := conn.Exec(ctx, "CREATE TABLE "+quote(schema)+`.decode_failure (id bigint DEFAULT 1, tenant text DEFAULT 'owner', active text DEFAULT 'not-a-bool', score bigint DEFAULT 0, name text DEFAULT 'persisted', note text)`); err != nil {
		t.Fatal(err)
	}
	bad, err := NewTable[testModel](schema, "decode_failure")
	if err != nil {
		t.Fatal(err)
	}
	if _, err := InsertOne(ctx, conn, bad); err == nil {
		t.Fatal("incompatible decode did not fail")
	}
	var persisted int
	if err := conn.QueryRow(ctx, "SELECT count(*) FROM "+quote(schema)+".decode_failure WHERE name='persisted'").Scan(&persisted); err != nil || persisted != 1 {
		t.Fatal("decode error incorrectly implied rollback", err)
	}
	// Canceled queries retain context classification and the connection remains
	// usable for an independent native count afterwards.
	canceled, stop := context.WithCancel(ctx)
	stop()
	if _, err := Select(canceled, conn, table, Query[testModel]{}); !errors.Is(err, context.Canceled) {
		t.Fatal("cancellation lost", err)
	}
	n, err = Delete(ctx, conn, table, And(id.Eq(first.ID), tenant.Eq("other")))
	if err != nil || n != 0 {
		t.Fatal(n, err)
	}
	n, err = Delete(ctx, conn, table, And(id.Eq(first.ID), tenant.Eq("owner")))
	if err != nil || n != 1 {
		t.Fatal(n, err)
	}
	var ownCount, shadowCount int
	if err := conn.QueryRow(ctx, "SELECT count(*) FROM "+quote(schema)+".records").Scan(&ownCount); err != nil {
		t.Fatal(err)
	}
	if err := conn.QueryRow(ctx, "SELECT count(*) FROM "+quote(shadow)+".records").Scan(&shadowCount); err != nil {
		t.Fatal(err)
	}
	if ownCount != 1 || shadowCount != 1 {
		t.Fatal("qualified isolation/cleanup counts", ownCount, shadowCount)
	}
}
