// gencode validates a bounded struct declaration and emits typed API metadata.
// Unsupported forms fail explicitly; this does not introspect a database.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"reflect"
	"strconv"
	"strings"
)

type field struct {
	name, db, typ string
	nullable      bool
}

func generate(input, model string) ([]byte, error) {
	f, err := parser.ParseFile(token.NewFileSet(), input, nil, 0)
	if err != nil {
		return nil, err
	}
	var st *ast.StructType
	for _, d := range f.Decls {
		g, ok := d.(*ast.GenDecl)
		if !ok || g.Tok != token.TYPE {
			continue
		}
		for _, s := range g.Specs {
			t := s.(*ast.TypeSpec)
			if t.Name.Name == model {
				st, _ = t.Type.(*ast.StructType)
			}
		}
	}
	if st == nil {
		return nil, fmt.Errorf("struct %s not found", model)
	}
	fields := []field{}
	seen := map[string]bool{}
	for _, f := range st.Fields.List {
		if f.Tag == nil {
			return nil, fmt.Errorf("all model fields require explicit db tag")
		}
		tag, err := strconv.Unquote(f.Tag.Value)
		if err != nil {
			return nil, err
		}
		db, ok := reflect.StructTag(tag).Lookup("db")
		if !ok {
			return nil, fmt.Errorf("missing db tag")
		}
		if db == "-" {
			continue
		}
		if len(f.Names) != 1 || !ast.IsExported(f.Names[0].Name) {
			return nil, fmt.Errorf("embedded, unexported or grouped fields unsupported")
		}
		parts := strings.Split(db, ",")
		if len(parts) > 2 || (len(parts) == 2 && parts[1] != "nullable") {
			return nil, fmt.Errorf("unknown db option %q", db)
		}
		if parts[0] == "" || seen[parts[0]] {
			return nil, fmt.Errorf("empty or duplicate db tag %q", parts[0])
		}
		seen[parts[0]] = true
		for _, r := range parts[0] {
			if !(r == '_' || r >= 'a' && r <= 'z' || r >= '0' && r <= '9') {
				return nil, fmt.Errorf("unsupported db identifier %q", parts[0])
			}
		}
		t := f.Type
		ptr := false
		if p, ok := t.(*ast.StarExpr); ok {
			ptr = true
			t = p.X
		}
		id, ok := t.(*ast.Ident)
		if !ok {
			return nil, fmt.Errorf("unsupported field type")
		}
		switch id.Name {
		case "int", "int64", "bool", "string":
		default:
			return nil, fmt.Errorf("unsupported field type %s", id.Name)
		}
		if ptr != (len(parts) == 2) {
			return nil, fmt.Errorf("pointer/nullability mismatch for %s", f.Names[0].Name)
		}
		typ := id.Name
		if ptr {
			typ = "*" + typ
		}
		fields = append(fields, field{f.Names[0].Name, parts[0], typ, ptr})
	}
	if len(fields) == 0 {
		return nil, fmt.Errorf("model has no mapped fields")
	}
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by go generate; DO NOT EDIT.\npackage %s\nimport (\"reflect\"; \"neutron.local/polyglot/go-codegen-spike/typed\")\n", f.Name.Name)
	fmt.Fprintf(&b, "type %sColumnSet struct {\n", model)
	for _, x := range fields {
		fmt.Fprintf(&b, "%s typed.Column[%s,%s]\n", x.name, model, x.typ)
	}
	fmt.Fprintln(&b, "}")
	fmt.Fprintf(&b, "func %sColumns() %sColumnSet { return %sColumnSet{\n", model, model, model)
	for _, x := range fields {
		fmt.Fprintf(&b, "%s:typed.NewColumn(%q,func(row %s) %s { return row.%s }),\n", x.name, x.db, model, x.typ, x.name)
	}
	fmt.Fprintln(&b, "} }")
	fmt.Fprintf(&b, "type %sWrite struct {\n", model)
	for _, x := range fields {
		fmt.Fprintf(&b, "%s typed.Optional[%s]\n", x.name, x.typ)
	}
	fmt.Fprintln(&b, "}")
	fmt.Fprintf(&b, "func (write %sWrite) Bindings() []typed.Binding { values:=[]typed.Binding{}\n", model)
	for _, x := range fields {
		if x.nullable {
			fmt.Fprintf(&b, "if value,ok:=write.%s.Get();ok { var bound any; if value!=nil { bound=*value };values=append(values,typed.Binding{Name:%q,Value:bound}) }\n", x.name, x.db)
		} else {
			fmt.Fprintf(&b, "if value,ok:=write.%s.Get();ok {values=append(values,typed.Binding{Name:%q,Value:value}) }\n", x.name, x.db)
		}
	}
	fmt.Fprintln(&b, "return values }")
	fmt.Fprintf(&b, "func %sMetadata() []typed.Field { return []typed.Field{\n", model)
	for _, x := range fields {
		fmt.Fprintf(&b, "{GoName:%q,DBName:%q,Type:reflect.TypeOf((*%s)(nil)).Elem(),Nullable:%t},\n", x.name, x.db, x.typ, x.nullable)
	}
	fmt.Fprintln(&b, "} }")
	fmt.Fprintf(&b, "func Validate%sMetadata() error { return typed.ValidateModel(reflect.TypeOf(%s{}),%sMetadata()) }\n", model, model, model)
	return format.Source(b.Bytes())
}

func main() {
	input := flag.String("input", "", "model source")
	output := flag.String("output", "", "generated file")
	model := flag.String("model", "", "struct name")
	flag.Parse()
	if *input == "" || *output == "" || *model == "" {
		fmt.Fprintln(os.Stderr, "input/output/model required")
		os.Exit(2)
	}
	b, err := generate(*input, *model)
	if err == nil {
		err = os.WriteFile(*output, b, 0644)
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
