#!/bin/sh
# Regenerate docs/CLI_REFERENCE.md and docs/CONFIG_REFERENCE.md from code.
#
#   sh scripts/gen-reference.sh
#
# CLI_REFERENCE.md is the verbatim `--help` output of the release binary (clap
# derives it from src/main.rs, so it cannot drift from the parser).
# CONFIG_REFERENCE.md is extracted from src/config/mod.rs: every serde field,
# its default function's value, its doc comment, and the environment variable
# that overrides it.
set -eu

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BIN="$ROOT/target/release/nucleus"
DOCS="$ROOT/docs"
CFG="$ROOT/src/config/mod.rs"
mkdir -p "$DOCS"

if [ ! -x "$BIN" ]; then
    echo "FAIL: $BIN not found — run 'cargo build --release' first" >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# CLI reference
# ---------------------------------------------------------------------------

OUT="$DOCS/CLI_REFERENCE.md"
{
    echo "# Nucleus CLI reference"
    echo
    echo "Generated by \`scripts/gen-reference.sh\` from the clap definitions in"
    echo "\`src/main.rs\`. Do not edit by hand — rerun the script instead."
    echo
    echo "Binary version: \`$("$BIN" --version)\`"
    echo
    echo '```'
    "$BIN" --help
    echo '```'
    echo
    # Subcommand list straight out of clap's help, so a new subcommand shows up
    # here without touching this script.
    SUBS=$("$BIN" --help | awk '/^Commands:/{f=1;next} /^Options:/{f=0} f && NF && $1 !~ /^-/ {print $1}')
    for sub in $SUBS; do
        [ "$sub" = "help" ] && continue
        echo "## \`nucleus $sub\`"
        echo
        echo '```'
        "$BIN" "$sub" --help
        echo '```'
        echo
    done
} > "$OUT"
echo "wrote $OUT"

# ---------------------------------------------------------------------------
# Config reference
# ---------------------------------------------------------------------------

OUT="$DOCS/CONFIG_REFERENCE.md"
{
    echo "# Nucleus configuration reference"
    echo
    echo "Generated by \`scripts/gen-reference.sh\` from \`src/config/mod.rs\`."
    echo "Do not edit by hand — rerun the script instead."
    echo
    echo "Nucleus reads \`<data-dir>/nucleus.toml\` at startup. Precedence, lowest"
    echo "to highest: built-in default, TOML file, \`NUCLEUS_*\` environment"
    echo "variable, command-line flag. A missing file is not an error — every key"
    echo "falls back to its default."
    echo

    awk '
    function flush_desc() { desc = ""; ndesc = 0 }
    # Collect the default_* function bodies first pass is impossible in one
    # pass, so stash them and resolve at END.
    /^fn default_[a-z0-9_]+\(\)/ {
        name = $2; sub(/\(.*/, "", name); curfn = name; next
    }
    curfn != "" && /^}/ { curfn = ""; next }
    curfn != "" {
        v = $0
        gsub(/^[ \t]+|[ \t]+$/, "", v)
        gsub(/\.to_string\(\)/, "", v)
        if (v != "") { defval[curfn] = v }
        next
    }
    /^pub struct [A-Za-z]+Config/ { sect = $3; sub(/Config$/, "", sect); flush_desc(); next }
    /^}/ { sect = ""; flush_desc(); next }
    sect != "" && /^[ \t]*\/\/\// {
        line = $0
        sub(/^[ \t]*\/\/\/[ ]?/, "", line)
        desc = (desc == "" ? line : desc " " line)
        next
    }
    sect != "" && /#\[serde\(default = "/ {
        d = $0; sub(/.*default = "/, "", d); sub(/".*/, "", d); pend = d; next
    }
    sect != "" && /#\[serde\(default\)\]/ { pend = "__unit"; next }
    sect != "" && /^[ \t]*pub [a-z_]+:/ {
        f = $2; sub(/:.*/, "", f)
        t = $0; sub(/.*: /, "", t); sub(/,.*/, "", t)
        printf "%s|%s|%s|%s|%s\n", tolower(sect), f, t, (pend == "" ? "-" : pend), desc
        pend = ""; flush_desc(); next
    }
    { flush_desc() }
    END {
        # nothing; defaults resolved by the second awk pass below
    }
    ' "$CFG" > /tmp/nucleus_cfg_fields.$$

    # Resolve default-function names to their literal values.
    awk '
    /^fn default_[a-z0-9_]+\(\)/ { name = $2; sub(/\(.*/, "", name); curfn = name; next }
    curfn != "" && /^}/ { curfn = ""; next }
    curfn != "" {
        v = $0; gsub(/^[ \t]+|[ \t]+$/, "", v); gsub(/\.to_string\(\)/, "", v)
        if (v != "") print curfn "\t" v
        curfn_done = 1; next
    }
    ' "$CFG" > /tmp/nucleus_cfg_defaults.$$

    cursect=""
    while IFS='|' read -r sect field type deffn desc; do
        if [ "$sect" != "$cursect" ]; then
            [ -n "$cursect" ] && echo
            echo "## \`[$sect]\`"
            echo
            echo "| Key | Type | Default | Env override | Description |"
            echo "|---|---|---|---|---|"
            cursect="$sect"
        fi
        case "$deffn" in
            __unit)
                case "$type" in
                    bool) def="false" ;;
                    Option*) def="(unset)" ;;
                    *) def="0" ;;
                esac ;;
            -) def="-" ;;
            *) def=$(awk -F'\t' -v k="$deffn" '$1==k{print $2}' /tmp/nucleus_cfg_defaults.$$) ;;
        esac
        [ -z "$def" ] && def="-"
        envvar=$(awk -v s="$sect" -v f="$field" '
            $0 ~ "env::var\\(\"NUCLEUS_" { v = $0; sub(/.*env::var\("/, "", v); sub(/".*/, "", v); pend = v }
            $0 ~ "self\\." s "\\." f " = " && pend != "" { print pend; exit }
        ' "$CFG")
        [ -z "$envvar" ] && envvar="-"
        [ -z "$desc" ] && desc="-"
        echo "| \`$field\` | \`$type\` | \`$def\` | \`$envvar\` | $desc |"
    done < /tmp/nucleus_cfg_fields.$$
    rm -f /tmp/nucleus_cfg_fields.$$ /tmp/nucleus_cfg_defaults.$$

    echo
    echo "## Every \`NUCLEUS_*\` variable read by the source tree"
    echo
    echo "Mechanically extracted (\`grep -o 'NUCLEUS_[A-Z_0-9]*'\` over \`src/\`)."
    echo "Variables under \`src/bin/\` or the fault-injection modules are test and"
    echo "probe hooks, not supported configuration."
    echo
    echo "| Variable | First read in |"
    echo "|---|---|"
    grep -rhoE '"NUCLEUS_[A-Z_0-9]+"' "$ROOT/src" | tr -d '"' | sort -u | while read -r v; do
        loc=$(grep -rl "\"$v\"" "$ROOT/src" | head -1 | sed "s|$ROOT/||")
        echo "| \`$v\` | \`$loc\` |"
    done
} > "$OUT"
echo "wrote $OUT"
