// Auto-generated by Neutron. Do not edit.
declare module "neutron" {
  interface NeutronGeneratedRouteMap {
    paths:
    | "/"
    | "/about"
    | "/admin"
    | "/api/cache"
    | "/api/mutate"
    | "/api/revalidate"
    | "/api/session/refresh"
    | "/api/stream"
    | "/big"
    | "/blog"
    | `/blog/${string}`
    | "/compute"
    | "/dashboard"
    | "/error-demo"
    | "/islands"
    | "/login"
    | "/protected"
    | "/todos"
    | "/users"
    | `/users/${string}`
  }
}

export {};
