#!/usr/bin/env node
// Regenerates the measured sections of ORM_CONFORMANCE.md from
// capabilities.nucleus.json, so the report's numbers can only come from a
// probe run (run.mjs --write), never from memory.
//
//   node conformance/live/orm/report.mjs          rewrite the generated block
//   node conformance/live/orm/report.mjs --check  fail if the block is stale or
//                                                 the prose cites a probe id that
//                                                 does not exist

import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const CAPS = path.join(HERE, "capabilities.nucleus.json");
const DOC = path.join(HERE, "ORM_CONFORMANCE.md");
const BEGIN = "<!-- BEGIN GENERATED by report.mjs from capabilities.nucleus.json; do not edit by hand -->";
const END = "<!-- END GENERATED -->";
const DRIVERS = ["pg", "postgres"];
const STATUSES = ["supported", "unsupported", "unknown"];

const caps = JSON.parse(readFileSync(CAPS, "utf8"));
const list = caps.capabilities;
const cell = (s) => String(s).replace(/\|/g, "\\|").replace(/\s+/g, " ").trim();
const clip = (s, n) => (s.length > n ? `${s.slice(0, n - 1)}…` : s);

function render() {
  const out = [];
  const src = caps.source ?? {};
  out.push("### Measured revision", "");
  out.push("| fact | value |", "|---|---|");
  out.push(`| engine | ${cell(caps.engine.raw)} |`);
  out.push(`| source commit (\`--write\` run) | \`${src.commit}\` |`);
  out.push(`| \`nucleus/\` tree SHA (the engine identity) | \`${src.nucleusTree}\`${src.nucleusDirty ? " (uncommitted changes under nucleus/ at run time)" : ""} |`);
  out.push(`| binary SHA-256 (provenance only; release builds are not bit-reproducible) | \`${src.binarySha256 ?? "not recorded"}\` |`);
  out.push(`| drivers | ${DRIVERS.map((d) => `\`${d}\` ${caps.drivers[d] ?? "not run"}`).join(", ")} |`);
  out.push(`| runtime | Node ${caps.runtime.node}, \`@neutron-build/sql\` ${caps.runtime.neutronSql} |`);
  out.push(`| recorded | ${caps.generatedAt} |`, "");

  out.push("### Totals", "");
  out.push("| driver | probes | supported | unsupported | unknown |", "|---|---|---|---|---|");
  for (const d of DRIVERS) {
    const n = (s) => list.filter((e) => e.status[d] === s).length;
    out.push(`| \`${d}\` | ${list.length} | ${STATUSES.map(n).join(" | ")} |`);
  }
  out.push("");
  const divergent = list.filter((e) => new Set(DRIVERS.map((d) => e.status[d])).size > 1);
  out.push(
    divergent.length === 0
      ? "Driver-divergent verdicts: none."
      : `Driver-divergent verdicts: ${divergent.map((e) => `\`${e.id}\` (${DRIVERS.map((d) => `${d} ${e.status[d]}`).join(", ")})`).join("; ")}.`,
    "",
  );

  const areas = [...new Set(list.map((e) => e.area))];
  out.push("### By area (supported / unsupported / unknown)", "");
  out.push(`| area | probes | ${DRIVERS.map((d) => `\`${d}\``).join(" | ")} |`, `|---|---|${DRIVERS.map(() => "---").join("|")}|`);
  for (const a of areas) {
    const rows = list.filter((e) => e.area === a);
    const triple = (d) => STATUSES.map((s) => rows.filter((e) => e.status[d] === s).length).join(" / ");
    out.push(`| ${a} | ${rows.length} | ${DRIVERS.map(triple).join(" | ")} |`);
  }
  out.push("");

  out.push("### Every probe", "");
  out.push("Evidence is the observed engine behaviour for non-`supported` verdicts (first driver that failed; object names carry a per-run random tag).", "");
  for (const a of areas) {
    out.push(`#### ${a}`, "");
    out.push(`| probe | ${DRIVERS.join(" | ")} | SQLSTATE | evidence |`, `|---|${DRIVERS.map(() => "---").join("|")}|---|---|`);
    for (const e of list.filter((x) => x.area === a)) {
      const bad = DRIVERS.find((d) => e.status[d] !== "supported");
      const states = [...new Set(Object.values(e.sqlstate ?? {}))].join(", ");
      const evidence = bad ? clip(cell(e.detail[bad] ?? ""), 180) : "";
      out.push(`| \`${e.id}\` | ${DRIVERS.map((d) => e.status[d]).join(" | ")} | ${states} | ${evidence} |`);
    }
    out.push("");
  }
  return out.join("\n");
}

const doc = readFileSync(DOC, "utf8");
const i = doc.indexOf(BEGIN);
const j = doc.indexOf(END);
if (i < 0 || j < i) {
  console.error(`orm-report: ${DOC} lacks the generated-block markers`);
  process.exit(1);
}
const next = `${doc.slice(0, i + BEGIN.length)}\n\n${render()}\n${doc.slice(j)}`;

const ids = new Set(list.map((e) => e.id));
const cited = [...doc.matchAll(/`((?:engine|relation|dml|constraint|codec|catalog|ddl|rls|lock|txn|orm)\.[a-z0-9_.-]+)`/g)].map((m) => m[1]);
const unknownIds = [...new Set(cited.filter((id) => !ids.has(id)))];

if (process.argv.includes("--check")) {
  let failed = false;
  if (next !== doc) {
    console.error("::error::ORM_CONFORMANCE.md is stale against capabilities.nucleus.json — run node conformance/live/orm/report.mjs and commit the result");
    failed = true;
  }
  for (const id of unknownIds) {
    console.error(`::error::ORM_CONFORMANCE.md cites probe \`${id}\`, which capabilities.nucleus.json does not record`);
    failed = true;
  }
  if (!failed) console.log(`orm-report: ORM_CONFORMANCE.md matches ${list.length} recorded probes`);
  process.exit(failed ? 1 : 0);
}

writeFileSync(DOC, next);
for (const id of unknownIds) console.error(`orm-report: warning: cites unknown probe \`${id}\``);
console.log(`orm-report: regenerated ${path.relative(process.cwd(), DOC)} from ${list.length} probes`);
